title: Your awesome title
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://astro36.github.io/"
keywords: ["blog", "test"]
timezone: Asia/Seoul
permalink: pretty

author:
  disqus:
  email: astr36@naver.com
  github: Astro36 # required
  google_analytics:
  name: Astro # required
  telegram: psj1026

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"
