#
###################################
# Site wide configuration
####################################
#
title: Astro36
email: astr36@naver.com
description: My Blog
url: "http://astro36.me/" # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Astro36
  avatar: astro.png
  job: "High School Student"
  bio: "Hello World!"
  email: astr36@naver.com
  disqus-shortname: astro36
  twitter: sj_astro #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-77377358-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Astro36 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: psj1026 #username
